# -*- coding: utf-8 -*-
"""Rasa_bot.ipynb

Automatically generated by Colaboratory.

"""

!pip install rasa==1.10.3

!pip install -U tables==3.6.1

!pip install -U ipython

!python -m spacy download en

!pip install nest_asyncio==1.3.3

import os
import rasa 
import nest_asyncio#used to run rasa in asynchronous more to the jupyter notebook session

nest_asyncio.apply()

print("event loop ready")

from rasa.cli.scaffold import create_initial_project #to create the initial project

#create a working directory and store the project there
project = 'test_project'
create_initial_project(project)

os.chdir(project)
print(os.listdir("."))

config = "config.yml"
training_files = "data/"
domain = 'domain.yml'
output = 'models/'

print(config, training_files, domain, output)

model_path = rasa.train(domain, config, training_files, output)

print(model_path)

"""Just to check if everything is running all okay or not"""

# from rasa.jupyter import chat

# endpoints = 'endpoints.yml'

# chat(model_path, endpoints)

"""Used to override any intents"""

# Commented out IPython magic to ensure Python compatibility.
# #@title
# %%writefile data/nlu.md
# 
# ## intent: course
# - I want a course
# - I want to enroll to a course
# - I want to learn 
# 
# ## intent:G
# - I need a g
# - Can i get a G
# - I want a g licence
# - tell me about g
# - full licence
# - G licence
# - G
# - g
# - full g licence
# - full G licence
# ## intent:G2
# - I need a g2
# - Can i get a G2
# - I want a g2 licence
# - tell me about g2
# - G2
# - g 2
# - g two
# - G two
# 
# ## intent:G1
# - i need a G1
# - i want a g1
# - can I get a g1
# - tell me about g1
# - G1
# - g1
# 
# ## intent:num_licence
# - i need [G1](cat) licence
# - is [G2](cat) licence
# - [G](cat) licence
# - can I get [G1](cat) licence?
# - I want [g1](cat) licence.
# - I want to get [g2](cat)
# - I am willing to get a [g](cat) licence
# 
# ## intent:drivers_licence
# - i want a driving licence
# - i need a driver's licence
# - i am looking for a driver's licence
# - how can I get a driver's licence
# - what to do to get a driving licence?
# - I want to get a licence
# - I want a licence 
# - I need a licence 
# - can I get a licence?
# 
# 
# 
# 
# ## intent:greet
# - hey
# - hello
# - hi
# - good morning
# - good evening
# - hey there
# 
# ## intent:goodbye
# - bye
# - goodbye
# - see you around
# - see you later
# 
# ## intent:affirm
# - yes
# - indeed
# - of course
# - that sounds good
# - correct
# 
# ## intent:deny
# - no
# - never
# - I don't think so
# - don't like that
# - no way
# - not really
# 
# ## intent:mood_great
# - perfect
# - very good
# - great
# - amazing
# - wonderful
# - I am feeling very good
# - I am great
# - I'm good
# 
# ## intent:mood_unhappy
# - sad
# - very sad
# - unhappy
# - bad
# - very bad
# - awful
# - terrible
# - not very good
# - extremely sad
# - so sad
# 
# ## intent:bot_challenge
# - are you a bot?
# - are you a human?
# - am I talking to a bot?
# - am I talking to a human?
#

"""Used to override any domain"""

# Commented out IPython magic to ensure Python compatibility.
# #@title
# %%writefile domain.md
# 
# intents:
#   - greet
#   - goodbye
#   - affirm
#   - deny
#   - mood_great
#   - mood_unhappy
#   - bot_challenge
#   - drivers_licence
#   - num_licence
#   - G1
#   - G2
#   - G
#   - course
# 
# responses:
#   utter_course:
#   - text: "You have shown willingness for a course. Course information will be sent to you shortly"
#   utter_G:
#   - text: "You have chosen to know about G driver's licence. More information will sent to you shortly"
#   utter_G2:
#   - text: "You have chosen to know about G2 driver's licence. More information will sent to you shortly"
#   utter_G1:
#   - text: "You have chosen to know about G1 driver's licence. More information will sent to you shortly"
#   utter_num_licence:
#   - text: "Which type of driving licence are you looking for in particular? (G1, G2 or G)"
#   utter_drivers_licence:
#   - text: "How can I help you today?"
# 
# 
# 
#   utter_greet:
#   - text: "Hey! How are you?"
# 
#   utter_cheer_up:
#   - text: "Here is something to cheer you up:"
#     image: "https://i.imgur.com/nGF1K8f.jpg"
# 
#   utter_did_that_help:
#   - text: "Did that help you?"
# 
#   utter_happy:
#   - text: "Great, carry on!"
# 
#   utter_goodbye:
#   - text: "Bye"
# 
#   utter_iamabot:
#   - text: "I am a bot, powered by Rasa."
# 
#   entities:
#   - cat
# 
# session_config:
#   session_expiration_time: 60
#   carry_over_slots_to_new_session: true
#

"""Used to override any stories"""

# Commented out IPython magic to ensure Python compatibility.
# #@title
# %%writefile data/stories.md
# 
# 
# ## getting course
# * greet
#   - utter_greet
# * course
#   - utter_course
# ## getting G1 licence
# * greet
#   - utter_greet
# * licence
#   - utter_drivers_licence
# * num_licence
#   - utter_num_licence
# * G1
#   - utter_G1
# 
# ## getting G2 licence
# * greet
#   - utter_greet
# * licence
#   - utter_drivers_licence
# * num_licence
#   - utter_num_licence  
# * G2
#   - utter_G2
# 
# ## getting G licence
# * greet
#   - utter_greet
# * licence
#   - utter_drivers_licence
# * num_licence
#   - utter_num_licence  
# * G
#   - utter_G
# 
# ## happy path
# * greet
#   - utter_greet
# * mood_great
#   - utter_happy
# 
# ## sad path 1
# * greet
#   - utter_greet
# * mood_unhappy
#   - utter_cheer_up
#   - utter_did_that_help
# * affirm
#   - utter_happy
# 
# ## sad path 2
# * greet
#   - utter_greet
# * mood_unhappy
#   - utter_cheer_up
#   - utter_did_that_help
# * deny
#   - utter_goodbye
# 
# ## say goodbye
# * goodbye
#   - utter_goodbye
# 
# ## bot challenge
# * bot_challenge
#   - utter_iamabot
#

"""Train model"""

model_path = rasa.train(domain, config, training_files, output)
print(model_path)

"""Run model"""

endpoints = "endpoints.yml"
chat(model_path, endpoints)

